services:
  web:
    build: ./website/whisky

  api:
    build: ./api
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
    command: sh -c "cd /app/cmd && air ./cmd/main.go -b 0.0.0.0"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
