apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: your-web-image:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-volume
        hostPath:
          path: /home/officeboi/Desktop/go-projects/golang-vpc-api-project/website/whisky
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer